services:
    portfolio:
        container_name: portfolio
        build:
            context: .
            dockerfile: Dockerfile
            args:
                CACHEBUST: ${CACHEBUST}
        ports:
            - "5000:5000"

    portfolio-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                CACHEBUST: ${CACHEBUST}
        ports:
            - "5000:5000"
